<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <RootNamespace>SaveAndQuit</RootNamespace>
    <AssemblyName>SaveAndQuit</AssemblyName>
    <Nullable>enable</Nullable>
    <UnityModules>CoreModule;IMGUIModule;InputLegacyModule;TextRenderingModule</UnityModules>
  </PropertyGroup>
</Project>
